const INDUSTRIES = [
'1-Pager',
'10K',
'2D Artist',
'2nd Unit Director of Photography',
'3D Animation Studio',
'3D Artist',
'3D Designer Portfolio',
'3D Printing and Industrial Design Service',
'3D Printing and Industrial Designer',
'3D Printing Service',
'5K',
'A Cappella Choir',
'A Cappella Music Portfolio',
'A Cappella Student Portfolio',
'A Cappella Teacher',
'A/C Contracting Firm',
'A/C Manufacturer',
'A/C Repair Service',
'A/V Consultant',
'A/V Equipment Manufacturer',
'Abbey',
'ABC Store',
'Abortion Clinic',
'Abrasive Blasting Service',
'Abroad Blog',
'AC Manufacturer',
'AC Repair Shop',
'Academic',
'Academic & Educational Blog',
'Academic CV',
'Academic Library',
'Academic Tutor',
'Academic Tutorials Blog',
'Academy of Drumming',
'Academy of Music',
'Academy of Music Production',
'Acai Food Truck',
'Acapella Ensemble',
'Accelerator Program',
'Accessories Pop-Up Shop',
'Accessories Shop',
'Accessories Store',
'Accommodation',
'Accordion Lesson Videos',
'Accordion Teacher',
'Accountant',
'Accounting Agency',
'Accounting Firm',
'Accounting School',
'Accounting Tutor',
'Acoustic Camp',
'Acoustic Guitar Camp',
'Acro Yoga Instructor',
'Acro Yoga Studio',
'Acrobatics Center',
'Acrobatics Club',
'Acrobatics Group',
'Acrodance Centre',
'Acroyoga Blogger',
'Acroyoga Center',
'Acroyoga Club',
'Acroyoga Group',
'Acroyoga Teacher',
'Acting Camp',
'Acting School',
'Action Film Release',
'Action TV Show Release',
'Active Wear Shop',
'Activewear Manufacturer',
'Activewear Shop',
'Activist Group',
'Actor',
'Actor Fan Club',
'Actor Portfolio',
'Actress',
'Actress Resume',
'Actuary',
'Acupuncture Clinic',
'Acupuncture Needle Manufacturer',
'Acupuncture School',
'Acupuncture Studio',
'Acupuncture Therapist',
'Acupuncturist',
'Ad Blog',
'Ad Club',
'Addiction Treatment Center',
'Adoptive Parent Blog',
'Adult Care Home',
'Adult Education Blog',
'Adult Education School',
'Adult Learning Blog',
'Adventure Blog',
'Adventure Club',
'Adventure Film Release',
'Adventure Guide',
'Adventure Photographer',
'Adventure Travel Blog',
'Adventure TV Show Release',
'Advertising Agency',
'Advertising Blog',
'Advertising Club',
'Advertising Community',
'Advertising Forum',
'Advertising Memorabilia Collector',
'Advertising Memorabilia Store',
'Advertising Photography Studio',
'Advertising Portfolio',
'Advertising Producer',
'Advice Blog',
'Advocate',
'Advocate Firm',
'Aerial Dance School',
'Aerial Photographer',
'Aerial Photography Group',
'Aerial Yoga Blog',
'Aerial Yoga Instructor',
'Aerial Yoga Studio',
'Aerial Yoga Teacher',
'Aerobatic Team',
'Aerobic Gymnastics Center',
'Aerobic Gymnastics Facility',
'Aerobics Coach',
'Aerobics Dance Institute',
'Aerobics Dance Studio',
'Aerobics Fansite',
'Aerobics Group',
'Aerobics Instructor',
'Aerobics Team',
'Aerobics Trainer',
'Aerospace Engineering Firm',
'Aerospace Manufacturer',
'Aesthetic Salon',
'Aesthetician',
'Aesthetician Portfolio',
'Aesthetics Blog',
'Aesthetics School',
'Affiliate Marketing Portfolio',
'African Cultural Heritage Organization',
'African Culture Club',
'African Culture Group',
'African Dance Coach',
'African Dance Teacher',
'African Language Immersion Program',
'African Studies Research Center',
'Afropraise Album Release',
'Afropraise Band',
'After School Club',
'Agricultural Consultant',
'Agricultural Consulting Firm',
'Agricultural Contractor',
'Agricultural Engineering Firm',
'Agricultural Journalist',
'Agricultural Researcher',
'Agricultural Support Service',
'Agriculture Community',
'Agriculture Company',
'Agriculture Forum',
'Agriculture Research Lab',
'Agriculture School',
'Agriculture Startup',
'Agriculture Technology Startup',
'Agritech Startup',
'Agtech Company',
'Air Compressor Repair Service',
'Air Conditioner Manufacturer',
'Air Conditioning Contracting Firm',
'Air Conditioning Contractor',
'Air Conditioning Repair Service',
'Air Duct Cleaning Service',
'Air Filter Manufacturer',
'Air Filter Store',
'Air Filter Supplier',
'Air Vent Cleaning Service',
'Aircraft Engine Manufacturer',
'Aircraft Manufacturer',
'Aircraft Rental Service',
'Airplane Club',
'Airplane Engine Manufacturer',
'Airplane Fansite',
'Airport Shuttle Service',
'Airport Transportation Service',
'Album Landing Page',
'Album Release',
'Alcohol Distributor',
'Alcohol Rehab Center',
'Alcoholic Beverage Store',
'Alcoholics Anonymous',
'All Terrain Vehicle Dealer',
'All Terrain Vehicle Repair Shop',
'All-Terrain Vehicle Manufacturer',
'All-You-Can-Eat Buffet',
'Alternative Healer',
'Alternative Health Center',
'Alternative Living Blog',
'Alternative Medicine Practitioner',
'Aluminum Manufacturer',
'Aluminum Welder',
'Alumni Networking Event',
'Alzheimer\'s Research Organization',
'Ambulance and Emergency Vehicle Manufacturer',
'Ambulance Manufacturer',
'American Bistro',
'American Diner Landing Page',
'American Diner Opening',
'American Restaurant',
'Americana Band',
'Ammunition Distributor',
'Ammunition Manufacturer',
'Amusement Arcade',
'Amusement Center',
'Amusement Equipment Manufacturer',
'Amusement Machine Supplier',
'Amusement Ride Supplier',
'Anatomical Illustrator',
'Anesthesiologist',
'Angel Investor Group',
'Animal Acupuncture Therapist',
'Animal Adoption Organization',
'Animal Advocacy Movement',
'Animal Behaviorist',
'Animal Blogger',
'Animal Breeder',
'Animal Cafe',
'Animal Care Equipment Manufacturer',
'Animal Care Provider',
'Animal Fan Club',
'Animal Film Release',
'Animal Groomer',
'Animal Hospital',
'Animal Kennel',
'Animal Lover Blog',
'Animal Lover Cafe',
'Animal Park',
'Animal Photographer',
'Animal Photography Studio',
'Animal Protection Organization',
'Animal Rescue Blog',
'Animal Rescue Organization',
'Animal Rescue Service',
'Animal Rights Group',
'Animal Rights Movement',
'Animal Rights Organization',
'Animal Shelter',
'Animal Trainer',
'Animal Welfare Organization',
'Animated Film Release',
'Animation Illustrator',
'Animation Portfolio',
'Animation Studio',
'Animation Video Producer',
'Animator',
'Anime Artist',
'Anime Character Designer',
'Anime Club',
'Anime Illustrator',
'Anniversary Celebration',
'Anorexia Treatment Center',
'Anthropology Research Lab',
'Antique Gift Shop',
'Antique Store',
'Anxiety Support Group',
'Apartment Complex Landing Page',
'Apartment Remodeling Contractor',
'Apartment Rental',
'Apartment Rental Agency',
'Apiculturist',
'App',
'App Developer',
'App Developer Portfolio',
'App Development Company',
'App Development Firm',
'App Landing Page',
'Apparel Manufacturer',
'Apparel Manufacturing Agency',
'Appliance Manufacturer',
'Appliance Parts Supplier',
'Appliance Repair Service',
'Appliance Store',
'Applied Mathematics Lab',
'Appraisal Agency',
'Appraiser',
'Aquarium',
'Aquarium Manufacturer',
'Aquarium Store',
'Aquatic Playground',
'Arabic Language School',
'Archaeological Illustrator',
'Archaeological Site',
'Archaeology Group',
'Archaeology Research Lab',
'Archer',
'Archery Blog',
'Archery Club',
'Archery Equipment Manufacturer',
'Archery Facility',
'Archery Fansite',
'Archery Gear and Supplies Manufacturer',
'Archery Group',
'Archery Manufacturer',
'Archery Teacher',
'Archery Team',
'Archery Team Fansite',
'Architect',
'Architect Portfolio',
'Architectural Design Studio',
'Architectural Forum',
'Architectural Tour Guide',
'Architecture Blog',
'Architecture Camp',
'Architecture Design Blogger',
'Architecture Firm',
'Architecture Guide',
'Architecture Illustrator',
'Architecture Lab',
'Architecture Photographer',
'Arranger',
'Art & Culture Blog & Podcast',
'Art & Design Blogger',
'Art & Design Inspiration Blog',
'Art Advisor',
'Art Appraisal Agency',
'Art Blog',
'Art Broker',
'Art Camp',
'Art Center',
'Art Class Site',
'Art Classes',
'Art Club',
'Art Collector',
'Art Community',
'Art Dealer',
'Art Director',
'Art Director Portfolio',
'Art Exhibition',
'Art Fan Club',
'Art Gallery',
'Art Gallery Blog',
'Art Guide',
'Art History Club',
'Art History Group',
'Art History Research Center',
'Art Instructor',
'Art Magazine',
'Art Materials Store',
'Art Museum',
'Art Photographer',
'Art Portfolio',
'Art Restoration Portfolio',
'Art School',
'Art School Project',
'Art Studio',
'Art Supplies Manufacturer',
'Art Teacher',
'Art Tour Guide',
'Artificial Intelligence Lab',
'Artificial Plant Supplier',
'Artisan Portfolio',
'Artisan-Made Fashion Online Store',
'Artisan-Made Footwear Online Store',
'Artisan-Made Jewelry Online Store',
'Artisan-Made Online Clothing Store',
'Artisan-Made Textile Design Store',
'Artisanal Home Decor Online Store',
'Artisanal Home Online Store',
'Artisanal Textile Design Online Store',
'Artist',
'Artist Blog',
'Artist Collective',
'Artist Cooperative',
'Artist Grant Foundation',
'Artist Portfolio',
'Artistic Photographer',
'Artists Guild',
'Artists Union',
'Arts & Crafts Blog',
'Arts & Crafts Blog & Forum',
'Arts & Crafts Forum',
'Arts & Crafts Instructor',
'Arts & Crafts Online Workshop',
'Arts & Crafts Pop-Up Shop',
'Arts & Crafts Pop-Up Store',
'Arts & Crafts School',
'Arts & Crafts Teacher',
'Arts Forum',
'Arts Organization',
'Arts Research Center',
'Asbestos Testing Service',
'Asian Cultural Heritage Organization',
'Asian Culture Club',
'Asian Food Truck',
'Asian Restaurant',
'Asian Restaurant Landing Page',
'Asphalt Paving Company',
'Assembly Hall',
'Assisted Living Facility',
'Association',
'Astrologer',
'Astrology Blogger',
'Astronomer',
'Astronomy Camp',
'Astronomy Club',
'Astronomy Fansite',
'Astronomy Lab',
'Athlete',
'Athletic Clothing Manufacturer',
'Athletic Club',
'Athletic Facility',
'Athletics Facility',
'Atomic Research Lab',
'Attorney',
'Attorney Blog',
'ATV Club',
'ATV Fansite',
'ATV Group',
'ATV Manufacturer',
'ATV Race Team',
'ATV Rentals',
'ATV Repair School',
'ATV Trade School',
'Audio Electronic Contractor',
'Audio Engineering Institute',
'Audio Engineering University',
'Audio Equipment Manufacturer',
'Audio Pop-Up Store',
'Audio Technician',
'Audio Video Equipment Distributor',
'Audio Visual Consultant',
'Audio Visual Consulting Firm',
'Audio Visual Equipment Rental Service',
'Audio Visual Equipment Repair Shop',
'Audio Visual Service',
'Audiologist',
'Audiovisual Equipment Repair Service',
'Auditing Accounting Firm',
'Auditing Firm',
'Auditor',
'Aura Reading Blog',
'Author',
'Author Blog',
'Author Book Event',
'Author Portfolio',
'Authors Forum',
'Autism Research Center',
'Auto Dealer',
'Auto Equipment Manufacturer',
'Auto Glass Business',
'Auto Insurance Agency',
'Auto Parts & Accessories Manufacturer',
'Auto Parts Store',
'Auto Racer',
'Auto Racing Fan Club',
'Auto Racing Team',
'Auto Repair Shop',
'Auto Wash',
'Auto Workers Union',
'Automobile Forum',
'Automobile Manufacturer',
'Automobile Workshop',
'Automotive Care Service',
'Automotive Design Portfolio',
'Automotive Design Studio',
'Automotive Designer Portfolio',
'Automotive Machine Shop',
'Automotive Mechanic School',
'Automotive Tune Up Service',
'AV Consultant',
'AV Consulting Firm',
'AV Equipment Supplier',
'Avant-garde Composer',
'Avant-Garde Trumpeter',
'Aviation Consultant',
'Aviation Consulting Firm',
'Aviation Operations Specialist',
'Aviation School',
'Award Ceremony',
'Awards Ceremony',
'Awning Distributor',
'Ayahuasca Ceremony',
'Ayahuasca Retreat',
'Ayurvedic Practitioner',
'B&B',
'B2B Startup Accelerator',
'Baby Development Consultant',
'Baby Development Expert',
'Baby Doll Manufacturer',
'Baby Equipment Manufacturer',
'Baby Equipment Rental Service',
'Baby Furniture Store',
'Baby Photographer',
'Baby Photography Studio',
'Baby Product Manufacturer',
'Baby Shower',
'Baby Store',
'Babysitting Agency',
'Babywear Manufacturer',
'Bach Party',
'Bachelor Party',
'Bachelorette Party',
'Back Up Singer Portfolio',
'Back-to-School Pop-Up Shop',
'Backing Singer Portfolio',
'Backing Vocalist',
'Backpack Manufacturer',
'Badminton Camp',
'Badminton Center',
'Badminton Coach',
'Badminton Equipment Manufacturer',
'Badminton Facility',
'Badminton Fansite',
'Badminton Player',
'Badminton Racket Manufacturer',
'Badminton Team',
'Badminton Trainer',
'Bagel Shop',
'Bake Sale',
'Baked Goods Delivery Service',
'Baked Goods Wholesaler',
'Baker',
'Bakery',
'Bakery-Baking Portfolio',
'Baking Blog',
'Baking Club',
'Baking Group',
'Baking Magazine',
'Baking Portfolio',
'Baking School',
'Baking Workshop',
'Ballerina Fansite',
'Ballet Camp',
'Ballet Club',
'Ballet Dancer Fansite',
'Ballet Dancer Portfolio',
'Ballet Fansite',
'Ballet Institute',
'Ballet Master',
'Ballet Photographer',
'Ballet School',
'Ballet Shoes Manufacturer',
'Ballet Slippers Manufacturer',
'Ballet Teacher',
'Ballet Tutor',
'Balloon Artist',
'Balloon Manufacturer',
'Balloon Ride Tour Agency',
'Balloon Store',
'Ballroom',
'Ballroom Dance Center',
'Ballroom Dance Coach',
'Ballroom Dance Photographer',
'Ballroom Dancing Club',
'Band',
'Band Electronic Press Kit',
'Band EPK',
'Band Photographer',
'Band Press Kit',
'Banjo Lesson Videos',
'Banjo Player',
'Banjo Player Portfolio',
'Bank Vault Manufacturer',
'Bankruptcy Attorney',
'Banquet',
'Banquet Facility',
'Baptism',
'Bar',
'Bar Chef',
'Bar Equipment Manufacturer',
'Bar Landing Page',
'Bar Mitzvah',
'Barbecue Repair Shop',
'Barbecue Restaurant',
'Barber School',
'Barber Shop',
'Barber Supply Store',
'Barista School',
'Bark Supplier',
'Barkeep',
'Barrister',
'Bartending School',
'Baseball Blog',
'Baseball Camp',
'Baseball Coach',
'Baseball Diamond',
'Baseball Equipment Manufacturer',
'Baseball Facility',
'Baseball Fan Club',
'Baseball Fansite',
'Baseball Field',
'Baseball League',
'Baseball Magazine',
'Baseball Manufacturer',
'Baseball Memorabilia Collector',
'Baseball Memorabilia Store',
'Baseball Player',
'Baseball Team',
'Baseball Team Fansite',
'Baseball Trainer',
'Baseball Umpires Association',
'Basketball Blog',
'Basketball Camp',
'Basketball Club',
'Basketball Coach',
'Basketball Court Contractor',
'Basketball Fan Club',
'Basketball League',
'Basketball Magazine',
'Basketball Manufacturer',
'Basketball Memorabilia Collector',
'Basketball Memorabilia Online Store',
'Basketball Officials Association',
'Basketball Player',
'Basketball Referees Association',
'Basketball Team',
'Basketball Team Fansite',
'Basketball Trainer',
'Bass Guitar Fansite',
'Bass Guitar Lesson Videos',
'Bass Guitar Player',
'Bass Guitar Student Portfolio',
'Bass Guitar Teacher',
'Bass Guitarist Portfolio',
'Bass Instructor',
'Bass Student Portfolio',
'Bass Tutor',
'Bassist',
'Bassist Portfolio',
'Bassoon Fansite',
'Bassoon Instructor',
'Bassoon Lesson Videos',
'Bassoon Student Portfolio',
'Bassoon Tutor',
'Bassoonist',
'Bassoonist Portfolio',
'Bastille Day',
'Bastille Day Parade',
'Bat Mitzvah',
'Bath & Body Pop-Up Shop',
'Bath & Body Pop-Up Store',
'Bath Bomb Manufacturer',
'Bathing Suit Store',
'Bathroom Design Company',
'Bathroom Supply Store',
'Batting Cages',
'Battlefield Site',
'Battleground',
'Bazaar',
'BBQ Grill Store',
'BBQ Restaurant',
'Beach Resort',
'Beach Shop',
'Beach Volleyball Camp',
'Beach Volleyball Club',
'Beach Volleyball Fansite',
'Beach Volleyball Group',
'Beach Volleyball Instructor',
'Beach Volleyball Officials Association',
'Beach Volleyball Player',
'Beach Volleyball Team',
'Beach Volleyball Team Fansite',
'Beach Volleyball Trainer',
'Beach Wedding',
'Beachwear Shop',
'Beautician',
'Beauty & Fashion Blog',
'Beauty & Make-Up Pop-Up Shop',
'Beauty Blog',
'Beauty Business',
'Beauty Camp',
'Beauty Care Product Shop',
'Beauty Forum',
'Beauty Parlour',
'Beauty Photography',
'Beauty Photography Studio',
'Beauty Portfolio',
'Beauty Product Reviews',
'Beauty Products Manufacturer',
'Beauty Salon',
'Beauty School',
'Beauty School Portfolio',
'Beauty Shop',
'Beauty Subscription Box',
'Beauty Supply Manufacturer',
'Beauty Supply Retailer',
'Beauty Supply Store',
'Beauty Treatment Clinic',
'Beauty Tutorials',
'Beauty Video Blog',
'Beauty Video Channel',
'Beauty Videos',
'Beauty YouTube Personality',
'Bed Linen Manufacturer',
'Bed Repair Service',
'Bedding Store',
'Bedroom Furniture Store',
'Bee Club',
'Bee Keeper',
'Beekeeper',
'Beekeepers Club',
'Beekeeping Blog',
'Beer Club',
'Beer Distributor',
'Beer Fan Club',
'Beer Fansite',
'Beer Garden',
'Beer Keg Manufacturer',
'Beer Lovers Club',
'beer store',
'Behavioral Hypnotherapist',
'Belly Dance Academy',
'Belly Dance Photographer',
'Belly Dancing Group',
'Belly Dancing Instructor',
'Belly Dancing Teacher',
'Bellydance Photographer',
'Bespoke Embroidery',
'Best Boy',
'Bestselling Author Store',
'Beverage Distributor',
'Beverage Manufacturer',
'Bible Blog',
'Bible Inspiration Blog',
'Bible Instructor',
'Bicycle Manufacturer',
'Bicycle Repair Service',
'Big Data Lab',
'Bike Dealer',
'Bike Rental Shop',
'Bike Repair Shop',
'Bike Shop',
'Biking Blog',
'Bikram Yoga Studio',
'Billboard Manufacturer',
'Billiard Hall',
'Billiards Camp',
'Billiards Club',
'Billiards Equipment Manufacturer',
'Billiards Fansite',
'Billiards Instructor',
'Billiards Player',
'Billiards Supply Store',
'Billiards Teacher',
'Billiards Team',
'Binary Options eBook',
'Binary Trader',
'Binary Trading Firm',
'Bioarchaeology Lab',
'BioCamp',
'Biochemistry Lab',
'Biochemistry Tutor',
'Bioenergy Lab',
'Bioengineering Lab',
'Biographer',
'Biography Film Coming Soon',
'Biography Film Release',
'Biography TV Show Release',
'Biological Anthropology Lab',
'Biologist',
'Biology Class Site',
'Biology Club',
'Biology Fan Club',
'Biology Fansite',
'Biology Group',
'Biology Instructor',
'Biology Lab',
'Biology School',
'Biology Teacher',
'Bioreserve',
'Biosphere Reserve',
'Biotechnology Manufacturer',
'Biotechnology Start-up',
'Biotechnology Startup',
'Bipolar Disorder Blog',
'Bird Fan Club',
'Bird Fansite',
'Bird Farm',
'Bird Photographer',
'Birding Camp',
'Birdwatching Club',
'Birdwatching Group',
'Birth Center',
'Birth Companion Collective',
'Birth Education',
'Birthday',
'Birthday Celebration',
'Birthday Party',
'Birthing Center',
'Birthing Classes',
'Birthing Doula',
'Birthing Guide',
'Bishop',
'Bitcoin App Landing Page',
'Bitcoin Club',
'Bitcoin Community',
'Bitcoin eBook Landing Page',
'Bitcoin Fan Club',
'Bitcoin Forum',
'Bitcoin Trader',
'Black & White Photographer',
'Black and White Photographer',
'Black and White Photography Studio',
'Black Tie Party',
'Blacksmith',
'Blinds Cleaning Service',
'Blinds Manufacturer',
'Blinds Store',
'Blockchain Meetup',
'Blog',
'Blog Coming Soon',
'Blog Under Construction',
'Blogger',
'Blood Doctor',
'Blown Glass Manufacturer',
'Blueberry Orchard',
'Blues Band',
'Blues Bar',
'Blues Blog',
'Blues Club',
'Blues Fansite',
'Blues Rock Band',
'Board Meeting',
'Boarding Cattery',
'Boarding School',
'Boat & Yacht Cleaning Service',
'Boat Charter',
'Boat Cleaning Service',
'Boat Club',
'Boat Dealer',
'Boat Dealership',
'Boat Detailing & Cleaning Service',
'Boat Manufacturer',
'Boat Rental Shop',
'Boat Repair Service',
'Boat Tour Agency',
'Boating Fan Club',
'Boating Fansite',
'Boating Instructor',
'Boating School',
'Boats & Water Craft Cleaning Service',
'Boba Tea Shop',
'Body Jewelry Manufacturer',
'Body Piercing Shop',
'Body Shop',
'Body-Mind Therapist',
'Bodybuilder',
'Bodybuilding Fansite',
'Bodyguard',
'Bollywood Music Band',
'Bon Voyage Party',
'Book Blogger',
'Book Club',
'Book Collector',
'Book Event',
'Book Fan Club',
'Book Illustrator',
'Book Landing Page',
'Book Launch',
'Book Lover Community',
'Book Publisher',
'Book Release',
'Book Retailer',
'Book Signing',
'Book Store',
'Booking Agency',
'Bookkeeping Service',
'Books Review Blog',
'Bookstore',
'Boot Camp',
'Booze Blog',
'Borehole Drilling Contractor',
'Bossa Nova Band',
'Botanic Illustrator',
'Botanical Garden',
'Botanical Photographer',
'Botanist',
'Botany Lab',
'Botany School',
'Bottled Water Manufacturer',
'Bottled Water Supplier',
'Bouldering Center',
'Bouldering Group',
'Bouldering Team',
'Bounce House Manufacturer',
'Bounce House Rental Store',
'Bouncy Castle Manufacturer',
'Bourbon Subscription Box',
'Boutique Clothing Shop',
'Boutique Law Firm',
'Boutique Recruitment Agency',
'Boutique Wines Pop-Up Shop',
'Boutique Wines Pop-Up Store',
'Bowler',
'Bowler Fansite',
'Bowling Alley',
'Bowling Blog',
'Bowling Center',
'Bowling Coach',
'Bowling Equipment Manufacturer',
'Bowling Group',
'Bowling Lounge',
'Bowling Teacher',
'Bowling Team',
'Boxer',
'Boxing Club',
'Boxing Equipment Manufacturer',
'Boxing Fan Club',
'Boxing Gloves Manufacturer',
'Boxing Gym',
'Boxing Magazine',
'Boxing Officials Association',
'Boxing Products Manufacturer',
'Boxing Referees Association',
'Boxing Team',
'Boxing Trainer',
'Boy Band',
'Boy Band Fan Club',
'Boys Camp',
'Brain Science Research Center',
'Brand Identity Developer',
'Brand Shoes Manufacturer',
'Branding Agency',
'Branding Consultant Portfolio',
'Branding Design Portfolio',
'Branding Portfolio',
'Brass Instrument Fansite',
'Brass Instrument Lesson Videos',
'Brass Player',
'Brass Player Portfolio',
'Brasserie',
'Brazilian Food Truck',
'Bread Delivery Service',
'Bread Making Club',
'Bread Making Group',
'Bread Shop',
'Break Dance Photographer',
'Breakdance Centre',
'Breakdance Photographer',
'Breakdance Teacher',
'Breakfast Cafe',
'Breakfast Diner',
'Breakfast Restaurant',
'Breastfeeding Consultant',
'Breathing and Respiratory Equipment Supplier',
'Brewery',
'Brewing Supply Distributor',
'Brick Manufacturer',
'Bricks and Mortar Supply Store',
'Bridal Boutique',
'Bridal Consultant',
'Bridal Consultant Company',
'Bridal Gown Store',
'Bridal Party',
'Bridal Rental Store',
'Bridal Shop',
'Bridal Shower',
'Bridal Stylist Portfolio',
'British Food Restaurant',
'Broadcast Designer',
'Broadcast Journalist',
'Broadcasting Equipment Manufacturer',
'Broadway Show',
'Broker',
'Brow Bar',
'Bubble Dining Pod',
'Bubble Tea Shop',
'Buddhism Blog',
'Buddhism Shop',
'Buddhism Store',
'Buddhism Temple',
'Buddhist Monastery',
'Buddhist Organization',
'Buddhist School',
'Buddhist Teacher',
'Buddhist Temple',
'Buddhist Tutor',
'Buddhist Volunteer Organization',
'Buffet Restaurant',
'Builder',
'Building Contractor',
'Building Contractor Company',
'Building Fund',
'Building Information Modelling Architect',
'Building Landing Page',
'Building Materials Manufacturer',
'Building Materials Store',
'Building Workers Union',
'Bulgarian Spice Manufacturer',
'Bulimia Hotline',
'Bulimia Nervosa Hotline',
'Bulimia Treatment Center',
'Bull Rider',
'Bull Rider Fansite',
'Bull Riding Fansite',
'Bunny Cafe',
'Burger Food Truck',
'Burger Restaurant',
'Burger Restaurant Coming Soon',
'Burger Restaurant Opening',
'Burmese Restaurant',
'Burrito Bar',
];

export default INDUSTRIES;
