/**
 * Template: Inside Mega Menu 3 (Pro)
 * Post Type: kadence_navigation
 */

import { createBlock } from '@wordpress/blocks';

const postMeta = {
	_kad_navigation_orientation: 'horizontal',
	_kad_navigation_stretchFill: 'fill',
	_kad_navigation_collapseSubMenus: '1',
	_kad_navigation_collapseSubMenusTablet: '1',
	_kad_navigation_collapseSubMenusMobile: '1',
	_kad_navigation_spacing: ['0', '0.5', '0', '0.5'],
	_kad_navigation_linkColor: 'palette3',
	_kad_navigation_linkColorHover: 'palette3',
	_kad_navigation_linkColorActive: 'palette3',
	_kad_navigation_background: 'palette9',
	_kad_navigation_backgroundHover: 'rgba(43, 108, 176, 0.1)',
	_kad_navigation_backgroundActive: 'rgba(43, 108, 176, 0.1)',
	_kad_navigation_typography: [
		{
			size: ['sm', '', ''],
			sizeType: 'px',
			lineHeight: ['', '', ''],
			lineType: '',
			letterSpacing: ['', '', ''],
			letterType: 'px',
			textTransform: '',
			family: '',
			google: false,
			style: '',
			weight: 'inherit',
			variant: '',
			subset: '',
			loadGoogle: true,
		},
	],
};

function innerBlocks() {
	return [
		createBlock('kadence/navigation', {}, [
			createBlock(
				'kadence/navigation-link',
				{
					uniqueID: '374_fd7683-b6',
					label: 'Short Title',
					description: 'Use this space to add a medium length description.',
					url: '#',
					mediaType: 'icon',
					mediaAlign: 'top',
					mediaColor: 'palette3',
					mediaColorHover: 'palette9',
					mediaColorActive: 'palette9',
					mediaBackground: 'rgba(43,108,176,0.1)',
					mediaBackgroundHover: 'palette1',
					mediaBackgroundActive: 'palette1',
					mediaBorderRadius: ['50', '50', '50', '50'],
					mediaStyle: [
						{
							color: 'palette3',
							colorTablet: '',
							colorMobile: '',
							colorHover: 'palette9',
							colorHoverTablet: '',
							colorHoverMobile: '',
							colorActive: 'palette9',
							colorActiveTablet: '',
							colorActiveMobile: '',
							background: 'rgba(43,108,176,0.1)',
							backgroundTablet: '',
							backgroundMobile: '',
							backgroundHover: 'palette1',
							backgroundHoverTablet: '',
							backgroundHoverMobile: '',
							backgroundActive: 'palette1',
							backgroundActiveTablet: '',
							backgroundActiveMobile: '',
							border: '',
							hoverBorder: '',
							borderRadius: 50,
							borderRadiusTablet: '',
							borderRadiusMobile: '',
							borderWidth: [0, 0, 0, 0],
							padding: [5, 5, 5, 5],
							paddingTablet: ['', '', '', ''],
							paddingMobile: ['', '', '', ''],
							paddingType: 'px',
							margin: [9, '', '', ''],
							marginTablet: ['', '', '', ''],
							marginMobile: ['', '', '', ''],
							marginType: 'px',
						},
					],
				},
				[]
			),
			createBlock(
				'kadence/navigation-link',
				{
					uniqueID: '374_22bf7e-36',
					label: 'Short title',
					description: 'Use this space to add a medium length description.',
					url: '#',
					kind: 'custom',
					mediaType: 'icon',
					mediaAlign: 'top',
					mediaColor: 'palette3',
					mediaColorHover: 'palette9',
					mediaColorActive: 'palette9',
					mediaBackground: 'rgba(43,108,176,0.1)',
					mediaBackgroundHover: 'palette1',
					mediaBackgroundActive: 'palette1',
					mediaBorderRadius: ['50', '50', '50', '50'],
					mediaStyle: [
						{
							color: 'palette3',
							colorTablet: '',
							colorMobile: '',
							colorHover: 'palette9',
							colorHoverTablet: '',
							colorHoverMobile: '',
							colorActive: 'palette9',
							colorActiveTablet: '',
							colorActiveMobile: '',
							background: 'rgba(43,108,176,0.1)',
							backgroundTablet: '',
							backgroundMobile: '',
							backgroundHover: 'palette1',
							backgroundHoverTablet: '',
							backgroundHoverMobile: '',
							backgroundActive: 'palette1',
							backgroundActiveTablet: '',
							backgroundActiveMobile: '',
							border: '',
							hoverBorder: '',
							borderRadius: 50,
							borderRadiusTablet: '',
							borderRadiusMobile: '',
							borderWidth: [0, 0, 0, 0],
							padding: [5, 5, 5, 5],
							paddingTablet: ['', '', '', ''],
							paddingMobile: ['', '', '', ''],
							paddingType: 'px',
							margin: [0, '', '', ''],
							marginTablet: ['', '', '', ''],
							marginMobile: ['', '', '', ''],
							marginType: 'px',
						},
					],
				},
				[]
			),
			createBlock(
				'kadence/navigation-link',
				{
					uniqueID: '374_7bfb70-25',
					label: 'Short Title',
					description: 'Use this space to add a medium length description.',
					url: '#',
					kind: 'custom',
					mediaType: 'icon',
					mediaAlign: 'top',
					mediaColor: 'palette3',
					mediaColorHover: 'palette9',
					mediaColorActive: 'palette9',
					mediaBackground: 'rgba(43,108,176,0.1)',
					mediaBackgroundHover: 'palette1',
					mediaBackgroundActive: 'palette1',
					mediaBorderRadius: ['50', '50', '50', '50'],
					mediaStyle: [
						{
							color: 'palette3',
							colorTablet: '',
							colorMobile: '',
							colorHover: 'palette9',
							colorHoverTablet: '',
							colorHoverMobile: '',
							colorActive: 'palette9',
							colorActiveTablet: '',
							colorActiveMobile: '',
							background: 'rgba(43,108,176,0.1)',
							backgroundTablet: '',
							backgroundMobile: '',
							backgroundHover: 'palette1',
							backgroundHoverTablet: '',
							backgroundHoverMobile: '',
							backgroundActive: 'palette1',
							backgroundActiveTablet: '',
							backgroundActiveMobile: '',
							border: '',
							hoverBorder: '',
							borderRadius: 50,
							borderRadiusTablet: '',
							borderRadiusMobile: '',
							borderWidth: [0, 0, 0, 0],
							padding: [5, 5, 5, 5],
							paddingTablet: ['', '', '', ''],
							paddingMobile: ['', '', '', ''],
							paddingType: 'px',
							margin: [0, '', '', ''],
							marginTablet: ['', '', '', ''],
							marginMobile: ['', '', '', ''],
							marginType: 'px',
						},
					],
				},
				[]
			),
			createBlock(
				'kadence/navigation-link',
				{
					uniqueID: '374_75cf22-1a',
					label: 'Short Title',
					description: 'Use this space to add a medium length description.',
					url: '#',
					kind: 'custom',
					mediaType: 'icon',
					mediaAlign: 'top',
					mediaColor: 'palette3',
					mediaColorHover: 'palette9',
					mediaColorActive: 'palette9',
					mediaBackground: 'rgba(43,108,176,0.1)',
					mediaBackgroundHover: 'palette1',
					mediaBackgroundActive: 'palette1',
					mediaBorderRadius: ['50', '50', '50', '50'],
					mediaStyle: [
						{
							color: 'palette3',
							colorTablet: '',
							colorMobile: '',
							colorHover: 'palette9',
							colorHoverTablet: '',
							colorHoverMobile: '',
							colorActive: 'palette9',
							colorActiveTablet: '',
							colorActiveMobile: '',
							background: 'rgba(43,108,176,0.1)',
							backgroundTablet: '',
							backgroundMobile: '',
							backgroundHover: 'palette1',
							backgroundHoverTablet: '',
							backgroundHoverMobile: '',
							backgroundActive: 'palette1',
							backgroundActiveTablet: '',
							backgroundActiveMobile: '',
							border: '',
							hoverBorder: '',
							borderRadius: 50,
							borderRadiusTablet: '',
							borderRadiusMobile: '',
							borderWidth: [0, 0, 0, 0],
							padding: [5, 5, 5, 5],
							paddingTablet: ['', '', '', ''],
							paddingMobile: ['', '', '', ''],
							paddingType: 'px',
							margin: [0, '', '', ''],
							marginTablet: ['', '', '', ''],
							marginMobile: ['', '', '', ''],
							marginType: 'px',
						},
					],
				},
				[]
			),
			createBlock(
				'kadence/navigation-link',
				{
					uniqueID: '374_e05329-8e',
					label: 'Short Title',
					description: 'Use this space to add a medium length description.',
					url: '#',
					kind: 'custom',
					mediaType: 'icon',
					mediaAlign: 'top',
					mediaColor: 'palette3',
					mediaColorHover: 'palette9',
					mediaColorActive: 'palette9',
					mediaBackground: 'rgba(43,108,176,0.1)',
					mediaBackgroundHover: 'palette1',
					mediaBackgroundActive: 'palette1',
					mediaBorderRadius: ['50', '50', '50', '50'],
					mediaStyle: [
						{
							color: 'palette3',
							colorTablet: '',
							colorMobile: '',
							colorHover: 'palette9',
							colorHoverTablet: '',
							colorHoverMobile: '',
							colorActive: 'palette9',
							colorActiveTablet: '',
							colorActiveMobile: '',
							background: 'rgba(43,108,176,0.1)',
							backgroundTablet: '',
							backgroundMobile: '',
							backgroundHover: 'palette1',
							backgroundHoverTablet: '',
							backgroundHoverMobile: '',
							backgroundActive: 'palette1',
							backgroundActiveTablet: '',
							backgroundActiveMobile: '',
							border: '',
							hoverBorder: '',
							borderRadius: 50,
							borderRadiusTablet: '',
							borderRadiusMobile: '',
							borderWidth: [0, 0, 0, 0],
							padding: [5, 5, 5, 5],
							paddingTablet: ['', '', '', ''],
							paddingMobile: ['', '', '', ''],
							paddingType: 'px',
							margin: [0, '', '', ''],
							marginTablet: ['', '', '', ''],
							marginMobile: ['', '', '', ''],
							marginType: 'px',
						},
					],
				},
				[]
			),
		]),
	];
}

export { postMeta, innerBlocks };
