/**
 * WordPress dependencies
 */
export const API_ROUTE_GET_IMAGES = '/kb-design-library/v1/get_images';
export const COLLECTION_SESSION_KEY = 'kadence_ai_current_collection';

import { __, sprintf } from '@wordpress/i18n';

export const PATTERN_CATEGORIES = { 
	'category': __( 'Category', 'kadence-blocks' ),
	'hero': __( 'Hero', 'kadence-blocks' ),
	'cards': __( 'Cards', 'kadence-blocks' ),
	'columns': __( 'Columns', 'kadence-blocks' ),
	'media-text': __( 'Media and Text', 'kadence-blocks' ),
	'counter-or-stats': __( 'Counter or Stats', 'kadence-blocks' ),
	'form': __( 'Form', 'kadence-blocks' ),
	'gallery': __( 'Gallery', 'kadence-blocks' ),
	'accordion': __( 'Accordion', 'kadence-blocks' ),
	'image': __( 'Image', 'kadence-blocks' ),
	'list': __( 'List', 'kadence-blocks' ),
	'location': __( 'Location', 'kadence-blocks' ),
	'logo-farm': __( 'Logo Farm', 'kadence-blocks' ),
	'team': __( 'Team', 'kadence-blocks' ),
	'post-loop': __( 'Post Loop', 'kadence-blocks' ),
	'pricing-table': __( 'Pricing Table', 'kadence-blocks' ),
	'slider': __( 'Slider', 'kadence-blocks' ),
	'tabs': __( 'Tabs', 'kadence-blocks' ),
	'testimonials': __( 'Testimonials', 'kadence-blocks' ),
	'title-or-header': __( 'Title or Header', 'kadence-blocks' ),
	'video': __( 'Video', 'kadence-blocks' ),
 };
 export const PATTERN_CONTEXTS = {
	'value-prop': __( 'Value Proposition', 'kadence-blocks' ),
	'products-services': __( 'Products or Services', 'kadence-blocks' ),
	'about': __( 'About', 'kadence-blocks' ),
	'achievements': __( 'Achievements', 'kadence-blocks' ),
	'call-to-action': __( 'Call to Action', 'kadence-blocks' ),
	'testimonials': __( 'Testimonials', 'kadence-blocks' ),
	'get-started': __( 'Get Started', 'kadence-blocks' ),
	'pricing-table': __( 'Pricing Table', 'kadence-blocks' ),
	'location': __( 'Location', 'kadence-blocks' ),
	'history': __( 'History', 'kadence-blocks' ),
	'mission': __( 'Mission', 'kadence-blocks' ),
	'profile': __( 'Profile', 'kadence-blocks' ),
	'team': __( 'Team', 'kadence-blocks' ),
	'work': __( 'Work', 'kadence-blocks' ),
	'faq': __( 'FAQ', 'kadence-blocks' ),
	'welcome': __( 'Welcome', 'kadence-blocks' ),
	'news': __( 'News', 'kadence-blocks' ),
	'blog': __( 'Blog', 'kadence-blocks' ),
	'contact-form': __( 'Contact', 'kadence-blocks' ),
	'subscribe-form': __( 'Subscribe', 'kadence-blocks' ),
	'careers': __( 'Careers', 'kadence-blocks' ),
	'donate': __( 'Donate', 'kadence-blocks' ),
	'events': __( 'Events', 'kadence-blocks' ),
	'partners': __( 'Partners', 'kadence-blocks' ),
 };
 export const CONTEXTS_STATES = {
	'value-prop': false,
	'products-services': false,
	'about': false,
	'achievements': false,
	'call-to-action': false,
	'testimonials': false,
	'get-started': false,
	'pricing-table': false,
	'location': false,
	'history': false,
	'mission': false,
	'profile': false,
	'team': false,
	'work': false,
	'faq': false,
	'welcome': false,
	'news': false,
	'blog': false,
	'contact-form': false,
	'subscribe-form': false,
	'careers': false,
	'donate': false,
	'events': false,
	'partners': false,
	'podcast': false,
 };
 export const CONTEXTS_IN_PAGES = {
	'value-prop': false,
	'products-services': false,
	'about': false,
	'achievements': false,
	'call-to-action': false,
	'testimonials': false,
	'get-started': false,
	'pricing-table': false,
	'location': false,
	'history': false,
	'mission': false,
	'profile': false,
	'team': false,
	'work': false,
	'faq': false,
	'welcome': false,
	'news': false,
	'blog': false,
	'contact-form': false,
	'subscribe-form': false,
	'careers': false,
	'donate': false,
	'events': false,
	'partners': false,
 };
 export const PAGE_CATEGORIES = { 
	'category': __( 'Category', 'kadence-blocks' ),
	'home': __( 'Home', 'kadence-blocks' ),
	'about': __( 'About', 'kadence-blocks' ),
	'contact': __( 'Contact', 'kadence-blocks' ),
	'pricing': __( 'Pricing', 'kadence-blocks' ),
	'services': __( 'Services', 'kadence-blocks' ),
	'blog': __( 'Blog', 'kadence-blocks' ),
};
