name: ESLint
run-name: '[ESLint] ${{ github.event.head_commit.message }}'

on:
  push:
  # pull_request:

# permissions:
#   contents: write
#   pull-requests: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # ESLint and Prettier must be in `package.json`
      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

      - name: Run linters
        run: npm run lint-js

      # - name: Auto-fix lint issues
      #   run: npm run lint-js-fix

      # - name: Commit auto-fixes
      #   run: |
      #     if git diff --quiet; then
      #       echo "No changes to commit"
      #       exit 0
      #     fi
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add -A
      #     git commit -m "chore: apply eslint fixes [skip ci]"
      #     git push
