on:
  workflow_call:
    inputs:
      zip_name:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  update_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Create WordPress Playground URL
        id: create_playground_url
        run: |
          # Base64 encode the blueprint JSON
          BLUEPRINT=$(echo '{
            "preferredVersions": {
              "php": "8.0",
              "wp": "latest"
            },
            "steps": [
              {
                "step": "installPlugin",
                "pluginData": {
                  "resource": "url",
                  "url": "https://evnt.is/test.zip?file=${{ inputs.zip_name }}.zip"
                },
                "options": {
                  "activate": true
                }
              },
              {
                "step": "installTheme",
                "themeData": {
                    "resource": "wordpress.org/themes",
                    "slug": "kadence"
                },
                "options": {
                    "activate": true
                }
              }
            ]
          }' | base64 -w 0)

          # Create the playground URL
          PLAYGROUND_URL="https://playground.wordpress.net/#${BLUEPRINT}"

          # Set output
          echo "url=$PLAYGROUND_URL" >> $GITHUB_OUTPUT

      - name: Add PR comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const zipUrl = 'https://evnt.is/test.zip?file=${{ inputs.zip_name }}.zip';
            const playgroundUrl = '${{ steps.create_playground_url.outputs.url }}';
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `🎉 Build artifacts

              - Download zip: [${zipUrl}](${zipUrl})
              - [Try it in WordPress Playground](${playgroundUrl})`
            });
